"""empty message

Revision ID: 48945f75771f
Revises: ad4cd628d4a4
Create Date: 2021-07-20 17:47:32.540397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48945f75771f'
down_revision = 'ad4cd628d4a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('superiors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.String(length=255), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('salary', sa.Float(), nullable=False),
    sa.Column('superior_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['superior_id'], ['superiors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    op.drop_table('superiors')
    # ### end Alembic commands ###
