"""Add full_name to Superior

Revision ID: 744112371c12
Revises: 48945f75771f
Create Date: 2021-07-21 14:27:53.527924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '744112371c12'
down_revision = '48945f75771f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('superiors', sa.Column('full_name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('superiors', 'full_name')
    # ### end Alembic commands ###
