"""only employee model

Revision ID: a6ebfbffa994
Revises: 744112371c12
Create Date: 2021-07-22 23:25:26.346246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6ebfbffa994'
down_revision = '744112371c12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('employees_superior_id_fkey', 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'employees', ['superior_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key('employees_superior_id_fkey', 'employees', 'superiors', ['superior_id'], ['id'])
    # ### end Alembic commands ###
