"""Change salary field to Float

Revision ID: ad4cd628d4a4
Revises: 0125628c0036
Create Date: 2021-07-20 17:39:39.302663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad4cd628d4a4'
down_revision = '0125628c0036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    op.drop_table('superiors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('superiors',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('superiors_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='superiors_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('employees',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('position', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hire_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('salary', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('superior_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['superior_id'], ['superiors.id'], name='employees_superior_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='employees_pkey')
    )
    # ### end Alembic commands ###
